spring:
  redis:
    host: 192.168.234.234
    password: redis
    port: 6379
    database: 14
  data:
    mongodb:
      host: 192.168.234.234
      port: 27017
      database: joker-im
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    visibility:
      FIELD: PUBLIC_ONLY


im:
  web-domain: www.jokerim.org


logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG