spring:
  redis:
    host: redis-mall.tst.jianke-inc.com
    password: redis_jk20190911
    port: 6379
    database: 14
    timeout:
  data:
    mongodb:
      host: mongodb-mall.tst.jianke-inc.com
      port: 27017
      database: joker-im

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    visibility:
      FIELD: PUBLIC_ONLY