spring:
  redis:
    host: 192.168.234.234
    password: redis
    port: 6379
    database: 14
  data:
    mongodb:
      host: 192.168.234.234
      port: 27017
      database: joker-im
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    visibility:
      FIELD: PUBLIC_ONLY



  codec:
    max-in-memory-size: 200MB

im:
  web-domain: jokerim.org
  # 上传文件的路径
  file-root-dir: joker_files

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    im.joker: debug